

-- for backward compatibility (with birthstones 1.2-git [2012])


minetest.register_alias("birthstones:alexandrite_pick", "birthstones:pick_alexandrite")
minetest.register_alias("birthstones:amethyst_pick", "birthstones:pick_amethyst")
minetest.register_alias("birthstones:aquamarine_pick", "birthstones:pick_aquamarine")
minetest.register_alias("birthstones:diamond_pick", "birthstones:pick_diamond")
minetest.register_alias("birthstones:emerald_pick", "birthstones:pick_emerald")
minetest.register_alias("birthstones:garnet_pick", "birthstones:pick_garnet")
minetest.register_alias("birthstones:opal_pick", "birthstones:pick_opal")
minetest.register_alias("birthstones:peridot_pick", "birthstones:pick_peridot")
minetest.register_alias("birthstones:ruby_pick", "birthstones:pick_ruby")
minetest.register_alias("birthstones:sapphire_pick", "birthstones:pick_sapphire")
minetest.register_alias("birthstones:topaz_pick", "birthstones:pick_topaz")
minetest.register_alias("birthstones:zircon_pick", "birthstones:pick_zircon")

minetest.register_alias("birthstones:alexandrite_axe", "birthstones:axe_alexandrite")
minetest.register_alias("birthstones:amethyst_axe", "birthstones:axe_amethyst")
minetest.register_alias("birthstones:aquamarine_axe", "birthstones:axe_aquamarine")
minetest.register_alias("birthstones:diamond_axe", "birthstones:axe_diamond")
minetest.register_alias("birthstones:emerald_axe", "birthstones:axe_emerald")
minetest.register_alias("birthstones:garnet_axe", "birthstones:axe_garnet")
minetest.register_alias("birthstones:opal_axe", "birthstones:axe_opal")
minetest.register_alias("birthstones:peridot_axe", "birthstones:axe_peridot")
minetest.register_alias("birthstones:ruby_axe", "birthstones:axe_ruby")
minetest.register_alias("birthstones:sapphire_axe", "birthstones:axe_sapphire")
minetest.register_alias("birthstones:topaz_axe", "birthstones:axe_topaz")
minetest.register_alias("birthstones:zircon_axe", "birthstones:axe_zircon")

minetest.register_alias("birthstones:alexandriteore", "birthstones:stone_with_alexandrite")
minetest.register_alias("birthstones:amethystore", "birthstones:stone_with_amethyst")
minetest.register_alias("birthstones:aquamarineore", "birthstones:stone_with_aquamarine")
minetest.register_alias("birthstones:diamondore", "birthstones:stone_with_diamond")
minetest.register_alias("birthstones:emeraldore", "birthstones:stone_with_emerald")
minetest.register_alias("birthstones:garnetore", "birthstones:stone_with_garnet")
minetest.register_alias("birthstones:opalore", "birthstones:stone_with_opal")
minetest.register_alias("birthstones:peridotore", "birthstones:stone_with_peridot")
minetest.register_alias("birthstones:rubyore", "birthstones:stone_with_ruby")
minetest.register_alias("birthstones:sapphireore", "birthstones:stone_with_sapphire")
minetest.register_alias("birthstones:topazore", "birthstones:stone_with_topaz")
minetest.register_alias("birthstones:zirconore", "birthstones:stone_with_zircon")

